version: "3.9"
services:
  georchestra-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - REPO_USER
        - REPO_PW
        - REPO_URL
    image: mtr.devops.telekom.de/geo-hub/georchestra-gateway:latest
