name: "Test pull request"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: "Checking out"
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: "Setting up Java"
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: 'maven'

    - name: "Build gateway"
      run: make install

    - name: "Run tests"
      run: make test

    - name: "Build docker image"
      run: make docker

    - name: "Remove SNAPSHOT jars from repository"
      run: |
        find .m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
